[en]
  languageName = "English"
  contentDir = "content"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = "Made with ❤️ by the club <a class='text-muted' href='https://www.epita.fr/association/back-to-basics/'>BackToBasics</a>"
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[fr]
  languageName = "Français"
  contentDir = "content"
  weight = 5
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    footer = "Fait avec le ❤️ par l'association <a class='text-muted' href='https://www.epita.fr/association/back-to-basics/'>BackToBasics</a>"
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Alert Text</a>'
